### PR TITLE
Update requirements

### PR DESCRIPTION
**Pull request by caternuson**
For #22. Add additional required libraries.

### CODE REVIEW

**Comment by caternuson** [comment]
Hmmm. So I think I understand why this is failing:

image

The other libraries (st7789, il0373) are deployed to pypi, but not ssd1681:
https://github.com/adafruit/Adafruit_CircuitPython_SSD1681/blob/main/setup.py.disabled

But I'm not sure what the solution is, other than deploy to pypi?

**Comment by ladyada** [comment]
oh yahh. ok well now that we have displayio support for blinka, i think they *should* be on pypi now right? @tannewt @makermelissa

**Comment by tannewt** [comment]
@lesamouraipourpre What else do we need to do here?

**Comment by lesamouraipourpre** [comment]
I could be wrong but based on the [Learn Guide](https://learn.adafruit.com/adafruit-tft-gizmo/circuitpython-displayio-quickstart), I think the ST7789 is the only needed driver for the Gizmo. I had changed the `requirements.txt` when doing the `max_size` PR without realizing that this PR existed.

As an aside, I agree with the comment above that the displayio drivers should be pushed to PyPI for use with Blinka

**Review by FoamyGuy — APPROVED** [review]
There are two Eink variations of Gizmo devices. Those two use the display drivers being added to requirements here.

These changes look good to me

**Pull request merged**
